# Generated by Django 3.1.5 on 2022-05-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_admins_userregion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admins',
            old_name='userRegion',
            new_name='region',
        ),
    ]
