# Generated by Django 3.1.5 on 2022-05-31 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_devices'),
    ]

    operations = [
        migrations.CreateModel(
            name='sharedevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(default='system', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(default='system', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveIntegerField(choices=[(0, 'inactive'), (1, 'active'), (2, 'deleted_by_owner')], default=1)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('sharedevices_status', models.CharField(choices=[('true', 'True'), ('false', 'False')], default='true', max_length=100)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.client')),
                ('device_pk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.devices')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
