# Generated by Django 3.1.5 on 2022-06-04 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_sharedevices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devices',
            options={},
        ),
    ]
